// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Notification/Alert.vue')['default']
    AudioPlayer: typeof import('./components/Posts/AudioPlayer.vue')['default']
    FamilyCard: typeof import('./components/FamilyCard.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    KeepSake: typeof import('./components/KeepSake.vue')['default']
    LoginForm: typeof import('./components/forms/LoginForm.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PostButton: typeof import('./components/Posts/PostButton.vue')['default']
    PostCard: typeof import('./components/Posts/PostCard.vue')['default']
    PostList: typeof import('./components/Posts/PostList.vue')['default']
    PostLoader: typeof import('./components/Posts/PostLoader.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignupForm: typeof import('./components/forms/SignupForm.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    VerifyEmail: typeof import('./components/forms/VerifyEmail.vue')['default']
  }
}
